apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-test-helm
  name: nginx-test-helm
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx-test-helm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
